version: '3.3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_HOST=Localhost
      - POSTGRES_DB=battlesuite
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 80:8000
    env_file:
      - ./.env
    links:
      - db:db
#    restart: always
  makemigration:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py makemigrations
    volumes:
      - ./:/usr/src/app/
  migration:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py migrate
    volumes:
      - ./:/usr/src/app/