# Generated by Django 3.1.2 on 2020-10-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_friend_hashtag_notification_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='agency',
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
