# Generated by Django 3.1.2 on 2020-10-22 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20201020_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaminvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('receive_status', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.team')),
            ],
            options={
                'verbose_name': 'Teaminvite',
                'verbose_name_plural': 'Teaminvites',
            },
        ),
    ]
