# Generated by Django 3.1.5 on 2021-02-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_livestreammessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to='uploads/tournaments/'),
        ),
    ]
