# Generated by Django 3.1.5 on 2021-02-18 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_tournament_cover_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_teamA', models.IntegerField()),
                ('points_teamB', models.IntegerField()),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('teamA', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teamA', to='core.team')),
                ('teamB', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teamB', to='core.team')),
            ],
        ),
    ]
