# Generated by Django 3.1.2 on 2020-10-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201012_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='bgimage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/user/'),
        ),
    ]
