# Generated by Django 3.1.2 on 2020-11-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mainuser_bgimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='gaming_platform',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
